baseurl: https://masherator.github.io/
languageCode: en-us
title: OMI Oriental Grocery
theme: omi
canonifyurls: true
menu:
  main:
      - Name: "Recipes"
        Url: "/recipes/"
        Weight: 1
      - Name: "Classes"
        Url: "/classes/"
        Weight: 4
